In [1]:
#INFO6105 - HW1 

In [2]:
#1). Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array.    
import numpy as np
x = [[1,2,3],[4,5,6]]
NumPy_Array = np.array(x)
print(NumPy_Array)

[[1 2 3]
 [4 5 6]]


In [3]:
#2). Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6.     
array = np.arange(1, 7).reshape(3, 2)

In [4]:
#3). Use one line to create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value. 
mean_value = np.mean(np.arange(2, 101, 2))

print(mean_value)

51.0


In [5]:
#4) Create an 3x3x3 array filled with arbitrary float numbers; and find the minimum and maximum values.   


array = np.random.rand(3, 3, 3)# Create a 3x3x3 array with arbitrary float numbers

min_value = np.min(array) # to find max value
max_value = np.max(array) # to find min value

print("Array:")
print(array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Array:
[[[0.56415084 0.89335875 0.27678383]
  [0.19970972 0.18140542 0.87581342]
  [0.67639465 0.34758723 0.93358549]]

 [[0.14729142 0.97032022 0.20526601]
  [0.706272   0.39952171 0.50605108]
  [0.31667283 0.03883823 0.66699731]]

 [[0.512806   0.25678805 0.54207016]
  [0.98274088 0.38579259 0.98417537]
  [0.13491371 0.34051133 0.94876458]]]
Minimum Value: 0.03883822511207413
Maximum Value: 0.9841753654463222


In [6]:
# 5) Create a 3x4 2D array filled with values from 10 to 21 (included)

array_2d = np.arange(10, 22).reshape(3, 4)

print(array_2d)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [7]:
# 6) Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

array_l10 = np.arange(5, 5 + 10 * 3, 3)
# 5 is the start val of array
# 10 is length of array 
# 3 is the step

print(array_l10)


[ 5  8 11 14 17 20 23 26 29 32]


In [8]:
# 7) Create a shape (10,10) array with arbitrary values; and find the memory size of this array.

array_test = np.random.rand(10, 10)# Creating a 10x10 array 

memory_size = array_test.nbytes

print("Memory Size:", memory_size, "bytes")


Memory Size: 800 bytes


In [9]:
# 8) Create a 1-d array of size 10 with arbitrary values but the fifth value should be 5. 

array_5 = np.random.rand(10)# Creating a 1D array with length of 10

array_5[4] = 5

print(array_5)


[0.77368907 0.51188614 0.62414345 0.11833138 5.         0.21045483
 0.5464845  0.88749333 0.84853134 0.09792006]


In [10]:
# 9) Create an array with values ranging from 10 to 49 (included); and reverse it then (first element becomes last).
import numpy as np

initial_array = np.arange(10, 50)# Create the initial array from 10 to 49


# Reverse the array
reverse_of_array = initial_array[::-1] # reverse of array

print(initial_array)
print(reverse_of_array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
# 10) Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time.   


np.random.seed(9) # to get the same value we run we use seed

array_32 = np.random.rand(3, 2)# np.random.rand --- uses the range[0,1)

print(array_32)


[[0.01037415 0.50187459]
 [0.49577329 0.13382953]
 [0.14211109 0.21855868]]


In [12]:
# 11) Create a 5x5 matrix with row values ranging from 0 to 4:  
'''[[0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]

 [0. 1. 2. 3. 4.]]'''

matrix = np.tile(np.arange(5), (5, 1)) 
# np.tile is used to repeat the values .. 5 means repeatition of rows and 1 means column

print(matrix)



[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [13]:
# 12). Add a border (filled with 0's) around an existing array:                                     6 points

'''[[1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1.]]'''


        
'''[[0. 0. 0. 0. 0. 0. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 1. 1. 1. 1. 1. 0.]

 [0. 0. 0. 0. 0. 0. 0.]]'''


existing_array = np.ones((5, 5))# Existing array


larger_array = np.zeros((7, 7))# Creating a larger array filled with 0's


larger_array[1:6, 1:6] = existing_array# Place the existing array within the larger array
# here is 1 is included and 6 is excluded in the above slicing.


print(larger_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [14]:
# 13) Create a 5x5 2-d array with values 1,2,3,4,5 on the diagonal 

array_5x5 = np.diag([1, 2, 3, 4, 5]) # function in numpy used to create diagnol array.

print(array_5x5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [15]:
# Then, make 1,2,3,4 move below the diagonal:
import numpy as np

# Create a 5x5 diagonal array with values 1, 2, 3, 4, 5 on the diagonal
array_5x5 = np.diag([1, 2, 3, 4, 5])

# Move 1, 2, 3, 4 below the diagonal
array_5x5[np.arange(4), np.arange(1, 5)] = np.arange(1, 5)
#np.arange(4) means rows
#np.arange(1,5) means columns but excluding 5 
#np.arange final means 1,4 add in columns

print(array_5x5)


[[1 1 0 0 0]
 [0 2 2 0 0]
 [0 0 3 3 0]
 [0 0 0 4 4]
 [0 0 0 0 5]]


In [16]:
# 14) Create a 10x10 2-d array with 1 on the border and 0 inside

import numpy as np

array_10 = np.zeros((10, 10))# Creating a zeroes 10x10 array 


# Setting the border to 1
array_10[0, :] = 1  # Top row will be 1
array_10[-1, :] = 1  # Bottom row will be 1
array_10[:, 0] = 1  # Leftmost column will be 1
array_10[:, -1] = 1  # Rightmost column will be 1

print(array_10)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
# 15)  Extract the integer part of a random array of positive numbers using 2 different methods, and the result should be an integer array.       
import numpy as np

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  
# Here 5 is desired array size 
# 10 is max value

integer_array_1 = random_array.astype(int) # converting into integer part using casting to int

print(random_array)
print("Using casting to int:")
print(integer_array_1)


[4.18508181 2.48101168 0.84059651 3.4549864  1.66776347]
Using casting to int:
[4 2 0 3 1]


In [18]:
##Operations on Numpy Arrays

In [19]:
# 1). Find the index of 5th repetition of number 1 in the given array x.             

# x: [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]

X = [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]


target = 1
indices = [i for i, num in enumerate(X) if num == target]
#If num is equal to the target that means 1, it will add the index i to the indices list

if len(indices) >= 5:
    index = indices[4]
else:
    index = -1

print("Index of the 5th repetition of 1:", index)



Index of the 5th repetition of 1: 8


In [20]:
# 2). Use np.arange to get an array [1, 2, 3, ..., 9]. Split x into 3 sub-arrays, the length of each sub-array is 4, 2, and 3.   

# Create an array from 1 to 9
x_1 = np.arange(1, 10)# since x why is used in before cells I named x_1

# Split x into sub-arrays with lengths 4, 2, and 3
Sub_Array1 = x_1[:4]
Sub_Array2 = x_1[4:6]
Sub_Array3 = x_1[6:]

print("Subarray 1:", Sub_Array1)
print("Subarray 2:", Sub_Array2)
print("Subarray 3:", Sub_Array3)


Subarray 1: [1 2 3 4]
Subarray 2: [5 6]
Subarray 3: [7 8 9]


In [21]:
# 3)  Use np.arange to generate the following 2D array:                

'''[[ 0., 1., 2., 3.],

 [ 4., 5., 6., 7.],

 [ 8., 9., 10., 11.],

 [ 12., 13., 14., 15.]]'''

array_16 = np.arange(16).reshape(4, 4)# 1to 15 elements ( 4 x 4 shape)

print(array_16)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
# Use np.split to split the array into left and right halves

left_half, right_half = np.split(array_16, 2, axis=1)# Splitting the array into left and right halves
# 2 is for the equal size splitting
# axis =1 to split columns if required for rows you use axis = 0


print("Left Half:")
print(left_half)

print("\nRight Half:")
print(right_half)


Left Half:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Right Half:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [23]:
# 4)  Given an 2D array:                                                

'''[[5,10,15],

 [20,25,30],

 [35,40,45]]

(1) Slicing to get the sub-array [[10,15], [25,30]]  (4 points)

(2) Getting individual element value "20"  (2 points)'''

#(1)

original_array = [[5, 10, 15], [20, 25, 30], [35, 40, 45]]

sub_array = [row[1:] for row in original_array[1:3]]# Slicing to get the sub-array #[[25, 30], [40, 45]]
# 1:3 means 1-2 -- [20, 25, 30], [35, 40, 45]
# row[1:] removing 1st element (index 0)

print(sub_array)

# (2)
element_value = original_array[1][0]# Getting the individual element value "20"

print(element_value)

[[25, 30], [40, 45]]
20


In [24]:
# 5)  Let x be an array:                                                  

'''[[ 1 2 3],

 [ 4 5 6]].
and y be an array

[[ 7 8 9],

 [10 11 12]].
Concatenate x and y so that a new array looks like

[[1, 2, 3, 7, 8, 9],

 [4, 5, 6, 10, 11, 12]]'''


x_new = np.array([[1, 2, 3], [4, 5, 6]])# since x why is used in before cells I named x_new
y_new = np.array([[7, 8, 9], [10, 11, 12]])# since y why is used in before cells I named y_new

# Concatenate x and y along axis 1 to create a new array
result_new = np.concatenate((x_new, y_new), axis=1)

# Print the result
print(result_new)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [25]:
# 6). Compute the min/max (min is divided by max) for each row for a given 2d array, in which integer values range from 1 to 10 [1,10) and shape is (5,3).Here requires a random seed to keep the same value from the random generator.

import numpy as np

np.random.seed(12) # to get same value everytime we run

array_this = np.random.randint(1, 10, size=(5, 3))
# Creating a random 2D array with values ranging from 1 to 10 and shape (5, 3)


# Compute the minimum and maximum for each row
min_values = np.min(array_this, axis=1)
max_values = np.max(array_this, axis=1)

# Calculate the min divided by max for each row
min_divided_by_max = min_values / max_values

# Print the original array and the min divided by max for each row
print("Original 2D Array:")
print(array_this)
print("\nMin divided by Max for Each Row:")
print(min_divided_by_max)


Original 2D Array:
[[7 2 3]
 [4 4 1]
 [7 2 5]
 [6 3 7]
 [1 6 9]]

Min divided by Max for Each Row:
[0.28571429 0.25       0.28571429 0.42857143 0.11111111]


In [26]:
# 7). Normalize a 5x5 random matrix:                          

#Tips: a normalization operates like: (the array - the mean)/the standard deviation


random_matrix = np.random.rand(5, 5)# Create a random 5x5 matrix


# Calculate the mean and standard deviation of the matrix
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean_value) / std_deviation

# Print the original and normalized matrices
print("Original 5x5 Random Matrix:")
print(random_matrix)
print("\nNormalized 5x5 Matrix:")
print(normalized_matrix)


Original 5x5 Random Matrix:
[[0.98364716 0.48153021 0.91253883 0.18987634 0.14797388]
 [0.90726736 0.68432507 0.95772873 0.45605092 0.56314114]
 [0.80126538 0.94317762 0.22335928 0.70293978 0.49994509]
 [0.20266072 0.62936457 0.14429873 0.05295153 0.16436803]
 [0.86622657 0.03742869 0.21764164 0.98656115 0.17284219]]

Normalized 5x5 Matrix:
[[ 1.40570613 -0.10738068  1.19142723 -0.98625485 -1.11252438]
 [ 1.17554208  0.50372441  1.32760315 -0.18416035  0.13854692]
 [ 0.85611413  1.28375461 -0.88535686  0.55981826 -0.05188902]
 [-0.94773021  0.33810561 -1.12359912 -1.39886617 -1.063122  ]
 [ 1.05186916 -1.44564291 -0.90258649  1.41448719 -1.03758584]]


In [27]:
# 8). Convert 3 arrays into a 1d array.                          \

'''arr1: 0,1,2

arr2: 3,4,5,6

arr3: 7,8,9
Generate the 3 arrays by numpy arange()'''

import numpy as np

# Generate the three arrays using np.arange()
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

result_q = np.concatenate((arr1, arr2, arr3))# Concatenate the three arrays into a single 1D array


# Print the resulting 1D array
print(result_q)



[0 1 2 3 4 5 6 7 8 9]


In [28]:
# 9)  Get all items between 15 and 55 from aa, math expression: [15,55].                  

#The aa is uniformly distributed integers in a 1D array (size=20) with given values (<100). Requires defining a seed.


# Set a seed for reproducibility
seed = 9
np.random.seed(seed)

# Generate the array of uniformly distributed integers
array_size = 20
min_value = 0
max_value = 100
aa = np.random.randint(min_value, max_value, size=array_size)
#np.random.randint helps to generate random intergers given a range

# Filter the values between 15 and 55
filtered_values = aa[(aa >= 15) & (aa <= 55)]

print(filtered_values)


[54 22 22 52 40 33]


In [29]:
# 10) Get the positions where elements of a and b match.                 

#a = np.array([1,2,3,2,3,4,3,4,5,6])

#b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Find positions where elements of a and b match
matched_positions = np.where(a == b)

print(matched_positions)


(array([1, 3, 5, 7]),)


In [30]:
# 11). Use arange() to create an array from 0 to 20 ( [0,20) ); replace all odd numbers with -1.

test_arr = np.arange(0,21)
test_arr[test_arr % 2 != 0] = -1

print(test_arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


In [31]:
# 12) Considering a four dimensions array (3,4,3,4) with the values 0-9 randomly, how to get sum over the last two axis at once?    

# Create a random four-dimensional array (3, 4, 3, 4) with values between 0 and 9
arr_4d = np.random.randint(0, 10, size=(3, 4, 3, 4))

result = np.sum(arr_4d, axis=(-1, -2))# Getting the Sum over the last two axes (axis=-1 and axis=-2) at once


print(result)


[[66 52 56 36]
 [27 42 50 52]
 [50 47 56 49]]
